# Project information
site_name: NOVA
site_url: https://securitybreak.io
site_author: Thomas Roccia - fr0gger_
site_description: The Prompt Pattern Matching
strict: false

# Repository
repo_name: fr0gger/nova-framework
repo_url: https://github.com/fr0gger/nova-framework
edit_uri: edit/main/docs/

# Copyright
copyright: "Copyright &copy; 2025 fr0gger"

theme:
  name: material
  logo: 'novalogo.svg'
  favicon: 'favicon.ico'
  icon:
    repo: fontawesome/brands/github 
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      toggle:
        icon: material/weather-night 
        name: Switch to dark mode
    
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: amber
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

  features:
    - content.tabs.link
    - content.code.annotate
    - content.code.copy
    - content.action.edit
    - content.code.select
    - content.tooltips
    - announce.dismiss
    - navigation.expand
    - navigation.indexes
    - navigation.path
    - navigation.tabs
    - navigation.instant
    - navigation.instant.preview
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.sections
    - navigation.tracking
    - navigation.top
    - search.suggest
    - toc.follow
    
    - search.highlight
    - navigation.tabs
    #- navigation.tabs.sticky
    - navigation.sections
    - navigation.indexes
    - content.tabs.link
    - content.tooltips
    - content.action.edit
    - content.action.view

plugins:
  - search
  - social

markdown_extensions:
  - tables
  - toc:
      permalink: true
      title: Page contents
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      pygments_lang_class: true
  - pymdownx.extra
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html

extra:
  version:
    provider: mike
  analytics:
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/heart
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/heart-broken
          name: This page could be improved
          data: 0
          note: >-
            Thanks for your feedback!
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/fr0gger
    #- icon: fontawesome/brands/python
      #link: https://pypi.org/project/nova
    - icon: fontawesome/brands/x-twitter
      link: https://twitter.com/fr0gger_

# https://www.mkdocs.org/user-guide/configuration/#validation
validation:
  omitted_files: warn
  absolute_links: warn
  unrecognized_links: warn

nav:
  - Home:
    - Home: index.md
    - Why Nova: home/why.md
    - Nova Rules: home/rules.md
    - Quickstarts:
      - Quickstarts: quickstarts/index.md
      - Installation: quickstarts/installation.md
      - Running Nova: quickstarts/running.md

  - Usecases:
    - Overview: usecases/index.md
    #- Architecture: usecases/architecture.md
    - Nova Hunting: usecases/overview.md
    - Ollama: usecases/ollama.md
    - OpenAI: usecases/openai.md
    - Anthropic: usecases/anthropic.md
